version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}example-api
    container_name: api-tce
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/